---
- name: Register Current User
  ansible.builtin.set_fact:
    host_user: "{{ ansible_facts.get('user_id') or ansible_facts.get('env', {}).get('USER') or lookup('ansible.builtin.env', 'USER') }}"
  when: host_user is not defined
